<?php

/**
 * Implements hook_block_info().
 */
function scrollspy_block_info() {
  $blocks = array();
  $blocks['scrollspy'] = array(
    'info' => t('Scrollspy Module Block'), //Module name
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}



/**
 * Implements hook_menu().
 * API: https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_menu/7
 */
function scrollspy_menu() {
	$items['admin/structure/block/add-scrollspy-block'] = array( //admin/structure/block/add-scrollspy-block <-- That's the path we really want
		'title' => 'Add Scrollspy Block',
		'description' => 'Attach Scrollspy to a view',
		'page callback' => 'drupal_get_form', //To make a form -- API: https://api.drupal.org/api/drupal/includes!form.inc/function/drupal_get_form/7
        'page arguments' => array('scrollspy_add_block_form'),
		'access callback' => 'user_access',
		'access arguments' => array('administer blocks'),
		'type' => MENU_LOCAL_ACTION,
	);
	
	return $items;
}


/**
 * Builds form for adding scrollspy blocks
 * API: https://api.drupal.org/api/drupal/developer%21topics%21forms_api_reference.html/7
 */

function scrollspy_add_block_form() {
	$form['scrollspy_blocks'] = array(
		'#type' => 'checkboxes',
		'#options' => drupal_map_assoc(array(
			t('Test 1'), 
			t('Test 2')
		)),
		'#title' => t('Select Views to Scrollspy.'),
		'#description' => t('The Scrollspy effect from Bootstrap will be applied to each selected View.'),
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);

	return $form;
}

/**
 * Submit function for scrollspy add block form
 * API: Look it up in Form API
 */
function scrollspy_add_block_form_submit($form, $form_state) {
	
	$scrollspy_blocks = $form_state['values']['scrollspy_blocks']
	
	//if (isset(['scrollspy_blocks[Test 1]'])) {
	//	$name = 'test';
	//}
}


/**
* Get the result of a view.
*
* Set $name = whatever is selected in a list. 
* Get list from Views names and id's
*
*
*
* @param string $name
*      The name of the view to retrieve the data from.
*      scrollspy-test-view
*      http://drupal.mywebclass.org/mywebclass/?q=scrollspy-test-view
*
* @param string $display_id
*      The display id. On the edit page for the view in question, you'll find
*      a list of displays at the left side of the control area. "Defaults"
*      will be at the top of that list. Hover your cursor over the name of the
*      display you want to use. An URL will appear in the status bar of your
*      browser. This is usually at the bottom of the window, in the chrome.
*      Everything after #views-tab- is the display ID, e.g. page_1.
*
* @param ...
*      Any additional parameters will be passed as arguments.
* @return
*      array
*          An array containing an object for each view item.
*
*function views_get_view_result($name, $display_id = NULL) {
*  $args = func_get_args();
*  array_shift($args); // remove $name
*  if (count($args)) {
*    array_shift($args); // remove $display_id
*  }
*
*  $view = views_get_view($name);
*  if (is_object($view)) {
*    if (is_array($args)) {
*      $view->set_arguments($args);
*    }
*    if (is_string($display_id)) {
*      $view->set_display($display_id);
*    }
*    else {
*      $view->init_display();
*    }
*    $view->pre_execute();
*    $view->execute();
*    return $view->result;
*  }
*  else {
*    return array();
*  }
*}
*/
